### ISSUE TITLE
Scale out of cf-api-server doesn't work beyond 5 replicas in cf-for-k8s

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/capi-k8s-release#67] opened 2020-09-07 10:33 UTC
We did a scalability tests on cf-for-k8s [v-0.6.0](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.6.0). We started with one replica of cf-apiserver and started pushing buildpack based apps. After certain number of apps we could see cf-apiserver fails with the following error
```
Waiting for app to start...
Unexpected Response
Response code: 503
CC code:       0
CC error code:
Request ID:    f4f086f1-0ae3-4f07-9f0d-471c6b8028fa::be866d01-d450-4acb-87f1-f504de7e92e0
Description:   {
  "description": "Instances information unavailable: No running instances",
  "error_code": "CF-InstancesUnavailable",
  "code": 220002
}
```
500s' get piled up then if increase the replicas ,it takes sometime to starting working again. You can correlate with the following graph.

![image](https://user-images.githubusercontent.com/29627753/92378264-29767580-f123-11ea-96f5-e0227d8849e2.png)

Again after certain apps push succeeded, it failed with the same error again. In the same phase we increased **replicas till 5 and able to push till 1600 Application instances  beyond which scaling doesn't help.**

Just for the note: we used the default configurations for the [capi](https://github.com/cloudfoundry/cf-for-k8s/tree/master/config/capi) deployment.

**Comment by cwlbraa** [comment] 2020-09-08 20:59
Hi @KesavanKing! Could you look for the associated log line in the cf-api-server logs? It should have a backtrace that we could use to narrow down what the issue is here.

**Comment by KesavanKing** [comment] 2020-09-09 12:57
Following are the error log messages which we get from capi:
```FAILED
Unexpected Response
Response code: 503
CC code:       0
CC error code:
Request ID:    d27900c8-4163-4e70-94ba-f1ef67854595::113dba44-8156-4018-87fe-1158206c40f4
Description:   {
  "description": "Instances information unavailable: No running instances",
  "error_code": "CF-InstancesUnavailable",
  "code": 220002
}
```

```
{"timestamp":"2020-09-04T03:26:28.841440757Z","message":"all_instances_for_app.error","log_level":"error","source":"cc.diego.instances_reporter","data":{"request_guid":"d27900c8-4163-4e70-94ba-f1ef67854595::ffa09e10-730d-4926-9c8b-e9b2a80a5c0f","error":"No running instances"},"thread_id":47026329335120,"fiber_id":47026327709520,"process_id":1,"file":"/cloud_controller_ng/lib/cloud_controller/diego/reporters/instances_reporter.rb","lineno":42,"method":"rescue in all_instances_for_app"}
```

### Other error logs:

**Warning message w.r.t to log-cache:**

```
{"timestamp":"2020-09-04T10:51:58.864750324Z","message":"rescuing GRPC Unavailable error: #<struct Struct::Status code=14, details=\"Socket closed\", metadata={}>","log_level":"warn","source":"cc.logcache.client","data":{"request_guid":"a5a4be3b-4d37-4509-9cc5-6022dc47ad6a::7cf2ec6c-2881-4ea2-9402-f6f9fea86c8d"},"thread_id":47145215417060,"fiber_id":47145211220640,"process_id":1,"file":"/cloud_controller_ng/lib/logcache/client.rb","lineno":57,"method":"rescue in with_request_error_handling"}
```
Log-cache was consuming high memory reported in this [issue](https://github.com/cloudfoundry/cf-k8s-logging/issues/36). So we thought this is impacting the capi and scaled to two replicas but didn't help out. We saw frequent warning logs.


**Failed to resolve update conflicts after retries** 

From our previous issue #48  , retry logic has been implemented in this (https://github.com/cloudfoundry/cloud_controller_ng/commit/9ea993cc9932146b16ebdb6d17ccf61487e10136) and now we could see failures after three retries.
```
{"timestamp":"2020-09-04T11:34:52.475991124Z","message":"Failed to resolve update conflicts after 3 retries: ","log_level":"error","source":"kubernetes.update_reapply","data":{"request_guid":"f6616f42-7600-41f4-81a0-a3a1c1c70a89::e5fd47a6-017b-4b71-82ad-9ad8906d8d92"},"thread_id":47196692167440,"fiber_id":47196690470320,"process_id":1,"file":"/cloud_controller_ng/lib/kubernetes/update_reapply_client.rb","lineno":43,"method":"block in retry_on_conflict"}
```
**Broken Pipe Error**
```
{"timestamp":"2020-09-04T10:19:16.239772697Z","message":"app_event_emitter.emit.failed","log_level":"error","source":"cc.runner","data":{"request_guid":"b4f88ce4-9486-475f-bf21-7d1acdd7a51b::3cb2ee2b-0458-4b53-a6b1-8b5df041a640","app_id":"a1205c04-22d5-459e-8ea4-f42bf0c3bf35","message":"Creating build for app with guid a1205c04-22d5-459e-8ea4-f42bf0c3bf35","error":"Broken pipe"},"thread_id":46951993395000,"fiber_id":46951987974220,"process_id":1,"file":"/cloud_controller_ng/lib/app_log_emitter.rb","lineno":12,"method":"rescue in emit"}
```

*We have all the logs in place ,if you need more logs please reach out to us on slack we will share the loki instance*

**Comment by KesavanKing** [comment] 2020-09-16 11:27
We tried another round of tests to check the max concurrent pushes. During that time we could see nginx container went for frequent restarts and we observed the following error message.
`2020/09/14 12:38:48 [info] 6#0: *4675 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 127.0.0.1, server: , request: "GET /healthz HTTP/1.1", upstream: "http://unix:/data/cloud_controller_ng/cloud_controller.sock:/healthz", host: "localhost:80" `

**Comment by KesavanKing** [comment] 2020-10-05 05:03
During the scale tests on cf-for-k8s [0.7.0 release](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.7.0) , we found one more issue. Most of the cf push was failing with the call to `/v3/process/UUID/stats` 

When we do a `cf curl /v3/processes/UUID/stats` the response time was shooting beyond 18 seconds. The relevant log which we found is 
```
{"timestamp":"2020-10-02T03:19:16.027511805Z","message":"stats_for_app.error","log_level":"info","source":"cc.diego.instances_reporter","data":{"request_guid":"5b1ea345-eebe-4aca-9c06-a99e7391ccb7::2515f881-0f2a-46df-8dec-388501673725","error":"No running instances"},"thread_id":47248886568360,"fiber_id":70325610875860,"process_id":1,"file":"/workspace/lib/cloud_controller/diego/reporters/instances_stats_reporter.rb","lineno":61,"method":"rescue in stats_for_app"}
```

**Comment by piyalibanerjee** [comment] 2020-10-19 20:48
@KesavanKing What were the results of your max concurrent push testing? What was the max you were able to achieve? We are planning to run our own scale tests to observe the max concurrent pushes, but it would be good to see if we are able to reproduce what you're seeing in your tests.

**Comment by KesavanKing** [comment] 2020-10-21 14:41
Hi @piyalibanerjee ,
We have tried varying from 10 to 40 concurrent pushes.  If we go beyond 20 concurrent pushes , we see lot of failures with unmarshalling error .
```
Error unmarshalling the following into a cloud controller error: no healthy upstream
```
When we go beyond ~600 apps, 20 concurrent pushes didn't sustain. So we stick with 10 concurrent pushes on high loads.
 In our recent [scale tests ](https://github.com/perf-cfk8s/docs/wiki/cf-for-k8s-1.0.0)for release 1.0.0 we kept 20 concurrent pushes and it behaved well.

May be we will do dedicated max-concurrent push tests for latest release and let you know the more granular details of it.

And worth noting it here, during  our last tests for max-concurrent push , we found this #70  latency issue.

**Comment by matt-royal** [comment] 2020-10-26 23:51
@KesavanKing We just concluded our own testing for concurrent push and saw a similar result. Beyond 20 concurrent pushes the cf-api-server will become unhealthy and then requests to it will result in a "no healthy upstream" response with a 503 status code. Scaling out your cf-api-server should allow you to increase the number of concurrent pushes. We expect cf-for-k8s should be able to handle ~20 concurrent pushes per cf-api-server instance.

Here are a few questions that will help us to better understand and address this issue:

In the original description of this issue you mention that scaling the cf-api-server beyond 5 instances did not appear to help.

1. What errors did you observe when you had more than 5 cf-api-servers?
2. What operations were you attempting to do at the time? 
3. If you were pushing apps concurrently, how many concurrent pushes were you attempting?

**Comment by KesavanKing** [comment] 2020-10-27 05:28
Hi @matt-royal ,
Thanks for the confirmation on the concurrent pushes.

Beyond 5 replicas, the whole push itself is not consistent. We try to scale out ,scale up the CAPI instances and  we saw different failovers. We have added all the error log messages which we observed during the tests  in the above comments. 

1. Referring all the error logs here too. 
[CF-StatesUnavailable](https://github.com/cloudfoundry/capi-k8s-release/issues/67#issuecomment-689545072)
[nginx container restart](https://github.com/cloudfoundry/capi-k8s-release/issues/67#issuecomment-693344667)
[ call fails to v3/processes/UUID/stats](https://github.com/cloudfoundry/capi-k8s-release/issues/67#issuecomment-703397074)
2. We were performing concurrent pushes operations. And a separate script which push a simple app --> start the app --> Check route availability--> Delete the app.

3. In recent [1.0.0](https://github.com/perf-cfk8s/docs/wiki/cf-for-k8s-1.0.0) scale tests we kept 20 concurrent pushes.

**Comment by matt-royal** [comment] 2020-10-27 05:53
@KesavanKing Thank you for that additional information. It sounds as though we should be able to reproduce the problem you're seeing with the following steps:

1. Scale up cf-api-server to 6 instances
2. Run a script to do 20 concurrent app pushes
3. Observe errors and logs for failed push operations for step 2

Does that sound right?

**Comment by KesavanKing** [comment] 2020-10-27 06:35
Yes perfect.

**Comment by matt-royal** [comment] 2020-11-10 23:45
@KesavanKing We weren't able to reproduce this issue. Here's what we did:

- Provision a GKE cluster with 20 nodes
- Deploy the standard cf-for-k8s to the cluster, then scale up the cf-api-server to 6 replicas
- Run 20 parallel `cf push` commands (using the dora app in cf-acceptance-tests) until we had a total of 60 apps on the platform.

One of the pushes failed due to a bad response from eirini, but that was the only error we saw.

**Comment by KesavanKing** [comment] 2020-11-17 15:49
Hi @matt-royal ,
> Again after certain apps push succeeded, it failed with the same error again. In the same phase we increased **replicas till 5 and able to push till 1600 Application instances beyond which scaling doesn't help.**

As stated in our first comment, you need to push more than 1600 applications.

**Comment by KesavanKing** [comment] 2020-12-18 03:56
FYI , in the latest scale tests on cf-for-k8s-1.1.0 also faced the same issue.
https://github.com/perf-cfk8s/docs/wiki/cf-for-k8s-1.1.0

**Comment by heycait** [comment] 2021-05-12 20:40
Given the conversation around converging on a [shared CF on K8s vision](https://docs.google.com/document/d/1rG814raI5UfGUsF_Ycrr8hKQMo1RH9TRMxuvkgHSdLg), we won’t be focused on scaling the current cf for k8s and are going to close the issue.

We’d recommend either commenting on the document to discuss scaling needs or attending the Cloud Foundry for Kubernetes SIG meeting on the calendar here: https://www.cloudfoundry.org/community-calendar/

**Closed by heycait** 2021-05-12 20:40 UTC
Labels: performance, unscheduled
