### ISSUE TITLE
`cf push` timeout related to kpack-watcher

### ISSUE THREAD

**Issue by jamespollard8** [cloudfoundry/capi-k8s-release#27] opened 2020-03-31 20:43 UTC
As discussed with @piyalibanerjee and @jspawar 

We noticed a [failed build](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/stability-test-cf-for-k8s/builds/2190) of smoketests on cf-for-k8s and starting digging in.

We observed that the completion container of the staging pod completed but showed ready=`false` - which we realized is the expected behavior (even for apps that are successfully pushed).

We next saw the `capi-kpack-watcher` logs which were surprisingly short (no details about app staging):
```
2020/03/30 23:36:51 Watcher initialized. Listening...
2020/03/30 23:36:51 [AddFunc] New Build: &{TypeMeta:{Kind:Build APIVersion:build.pivotal.io/v1alpha1} ObjectMeta:{Name:eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw GenerateName:eec29581-395d-4841-adee-d1c37c146684-build-1- Namespace:cf-workloads-staging SelfLink:/apis/build.pivotal.io/v1alpha1/namespaces/cf-workloads-staging/builds/eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw UID:0d60fe53-0c1b-4c0f-a005-02ee797e8d95 ResourceVersion:1487666 Generation:1 CreationTimestamp:2020-03-30 23:36:48 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[cloudfoundry.org/app_guid:a4bb542b-bf81-4a26-9ff2-28f3734cfd37 cloudfoundry.org/build_guid:5266c24f-dece-49a6-a2b8-e196724c35b2 cloudfoundry.org/source_type:STG image.build.pivotal.io/buildNumber:1 image.build.pivotal.io/image:eec29581-395d-4841-adee-d1c37c146684] Annotations:map[image.build.pivotal.io/reason:CONFIG sidecar.istio.io/inject:false] OwnerReferences:[{APIVersion:build.pivotal.io/v1alpha1 Kind:Image Name:eec29581-395d-4841-adee-d1c37c146684 UID:e22d0931-859e-4e2b-9ce4-7858f4f3a44d Controller:0xc000400079 BlockOwnerDeletion:0xc000400078}] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[]} Spec:{Tags:[gcr.io/cf-relint-greengrass/cf-workloads/eec29581-395d-4841-adee-d1c37c146684 gcr.io/cf-relint-greengrass/cf-workloads/eec29581-395d-4841-adee-d1c37c146684:b1.20200330.233648] Builder:{Image:index.docker.io/cloudfoundry/cnb@sha256:0a718640a4bde8ff65eb00e891ff7f4f23ffd9a0af44d43f6033cc5809768945 ImagePullSecrets:[]} ServiceAccount:cc-kpack-registry-service-account Source:{Git:<nil> Blob:0xc0003ef860 Registry:<nil> SubPath:} CacheName: Env:[] Resources:{Limits:map[] Requests:map[]} LastBuild:<nil>} Status:{Status:{ObservedGeneration:1 Conditions:[{Type:Succeeded Status:False Severity: LastTransitionTime:{Inner:2020-03-30 23:36:50 +0000 UTC} Reason: Message:pods "eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod" already exists}]} BuildMetadata:[] Stack:{RunImage: ID:} LatestImage: PodName:eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod StepStates:[] StepsCompleted:[]}}
```

The content of note from that long log line is `Reason: Message:pods "eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod" already exists`, which we've only observed before when trying to restage an existing app, which is currently not supported. (But also is not the case here as this was a new `cf push`)

Looking more carefully at the `capi-kpack-watcher` definition, we noticed that it had restarted once. Looking at the timestamps, we see that it came back up at 16:36:51 which is about 10 seconds after the cf push was executed. Looking at the timestamps from the short kpack-watcher logs above, we see that the build pod was created a few seconds before the kpack-watcher came back up.

```
  capi-kpack-watcher:
    Container ID:   docker://941b7763fec87f9fdadcb4c7d60322f8ca6486b16d7cdde2c803c32b888a01b1
    Image:          cloudfoundry/capi-kpack-watcher:latest
    Image ID:       docker-pullable://cloudfoundry/capi-kpack-watcher@sha256:6e6a3778953aa2b998e933fda726f18f5da89aa6b5738005efc22abd727a69dc
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 30 Mar 2020 16:36:51 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 30 Mar 2020 16:33:09 -0700
      Finished:     Mon, 30 Mar 2020 16:36:50 -0700
    Ready:          True
    Restart Count:  1
```

As far as the kpack-watcher container restarting, we've grabbed the full end of the log [here in this gist](https://gist.github.com/jamespollard8/334275ee062b9a95382942c396b21f6d) but here's a good, relevant section:
```
reason: map[image.build.pivotal.io/reason:CONFIG sidecar.istio.io/inject:false]
E0330 23:36:50.348158       1 runtime.go:73] Observed a panic: runtime.boundsError{x:-1, y:0, signed:true, code:0x0} (runtime error: index out of range [-1])
goroutine 5 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x12102e0, 0xc0000448c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x12102e0, 0xc0000448c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
capi_kpack_watcher/watcher.(*BuildWatcher).handleFailedBuild(0xc0002ec7e0, 0xc00011e280)
	/capi-kpack-watcher/watcher/build_watcher.go:144 +0x3a7
capi_kpack_watcher/watcher.(*BuildWatcher).UpdateFunc(0xc0002ec7e0, 0x12b1820, 0xc0000e9b80, 0x12b1820, 0xc00011e280)
	/capi-kpack-watcher/watcher/build_watcher.go:48 +0x2cb
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/controller.go:202
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc00005c5c8, 0x41720e, 0x7f1db97fc730)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-
...
f2f3a405f61d/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]
```

**Comment by aashah** [comment] 2020-04-30 23:44
Lot to unpack here. We have a couple general remarks, a timeline of what we think may have happened, and some followup for us/kpack/someone to explore

## Some remarks first,

> We next saw the capi-kpack-watcher logs which were surprisingly short (no details about app staging)

capi-kpack-watcher does not do the staging, kpack does. You will not find
app staging logs in capi-kpack-watcher, you'd have to found the appropriate build pod
in "cf-workloads-staging" namespace to tail logs.

> The content of note from that long log line is Reason: Message:pods "eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod" already exists, which we've only observed before when trying to restage an existing app

This is not true. The error we used to get when trying to restage an app is:

```json
{"error_code"=>"UnknownError", "description"=>"An unknown error occurred.", "code"=>10001, "test_mode_info"=>{"description"=>"images.build.pivotal.io \"9fa6af81-8366-4369-a69d-7f6d0d596688\" already exists", "error_code"=>"CF-HttpError", "backtrace"=>[...]}}
```

This error was coming from CC trying to recreate the same `Image`. Your error is closer to a build Pod...We have no idea why this error is emitted.

> runtime error: index out of range [-1]

This one is totally on us. We wrote some bad code.

Dev note: this comes from `BuildWatcher#handleFailedBuild` in `build_watcher.go:144`. We should probably check that the len(slice) is > 0 before trying to index into it.

## Timeline

This is our best guess as to what happened

1. cf push
1. the build pod in "cf-workloads-staging" comes up
1. build failed
1. capi-kpack-watcher panics from that -1
1. capi-kpack-watcher stops
1. capi-kpack-watcher comes back up (10 seconds after cf push)
    a. We see the "New Build" output here
1. cf push times out

The key detail here, is that we think some other reason caused the build to fail, and that we just did not handle the issue well. Instead, capi-kpack-watcher panicked, and never told CC about the failed build.

## Followup

It was really help to have the `Build` object. If we condense it down, we think the two problematic pieces will become more highlighted:

```json
Build{
    StepsCompleted: [],
    Status: {
        Type: Succeeded,
        Status: False,
        Reason: 'pods "eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod" already exists'
    }
}
```

We can fix the `panic: index out of range` super easy. Hopefully this will stop masking the other error (what we believe to be the root cause) of "pod already exists". We can followup with the kpack team to see if they can share any insight.

- Aakash && @reneighbor

**Comment by aashah** [comment] 2020-05-04 17:42
Started a conversation with the kpack team here - https://cloudfoundry.slack.com/archives/CUWG5TXB5/p1588291525034600

**Comment by aashah** [comment] 2020-05-04 22:07
In speaking with someone on the kpack team, they're interested in the following information to further debug the "pod already exists" error message. If it's still available on the environment, here's what they are requesting:

* The image/build/pod resources related to `eec29581-395d-4841-adee-d1c37c146684-build-1-8lzkw-build-pod`
* kpack (not capi-kpack-watcher) logs
* snapshot of the world

Please feel free to share that here if there is not any sensitive information. Otherwise please send it on Slack, my username is `@ashah`

- Aakash

**Comment by jamespollard8** [comment] 2020-05-06 04:52
Unfortunately that environment is long gone and we have no additional logs.

Thanks a bunch for the thorough investigation and write-up.

**Comment by aashah** [comment] 2020-05-08 01:24
No worries, I fixed the immediate issue of the `panic`, but it is just masking the real error, and the kpack team is looking for those resources to be able to debug it further.

I'm going to close the issue as it stands, since there is nothing more we can do in capi-k8s-release (until further debugging). We should absolutely keep an eye for this issue again though.

**Closed by aashah** 2020-05-08 01:24 UTC
Labels: unscheduled
