### ISSUE TITLE
EXPOSE port for non-8080 Docker apps not respected

### ISSUE THREAD

**Issue by reneighbor** [cloudfoundry/capi-k8s-release#86] opened 2020-10-20 23:43 UTC
Repo steps:
`cf enable-feature-flag diego_docker`
`cf push console -o splatform/stratos:stable`
`kubectl describe service -n cf-workloads [app service name]`

Stratos app exposes port 5443: https://github.com/cloudfoundry/stratos/blob/7519e6ab5570fc75b471ce6679a75df7d262b3c1/deploy/Dockerfile.all-in-one#L42
Expected Behavior: TargetPort is 5443, per EXPOSE directive in Dockerfile
Actual Behavior: TargetPort is 8080.

Tim says: "the route and destination is created before the docker app is staged. at that point there is no execution metadata so it creates it with the default 8080" 
https://app.slack.com/client/T02FL4A1X/threads/thread/C017LDM6KTQ-1603233260.197100

**Comment by tcdowney** [comment] 2020-10-21 21:30
### Cause

> "the route and destination is created before the docker app is staged. at that point there is no execution metadata so it creates it with the default 8080"

To elaborate on this... during `cf push` the cf CLI will create/map-route before the app is uploaded and staged. For Docker apps "staging" involves looking up metadata about the container image, such as exposed ports, and reporting those back to Cloud Controller to save off on the droplet. This is how Cloud Controller will discover that the Docker app wants to listen on port `5443` in this case.

But since we made the route and mapped it to this app before this happened, so Cloud Controller defaulted the port to `8080` (see [this code](https://github.com/cloudfoundry/cloud_controller_ng/blob/76db5c0ba6567336a39f944bdcba7fe78956c808/app/models/runtime/route_mapping_model.rb#L53)) and used that default port when [creating the corresponding Route CRD](https://github.com/cloudfoundry/cloud_controller_ng/blob/76db5c0ba6567336a39f944bdcba7fe78956c808/lib/kubernetes/route_resource_manager.rb#L73) on Kubernetes. That's the cause of the invalid port.

---

### So what can users do right now as a workaround?

1. You can use the v3 API to manually set the destination to the correct port prior to pushing the app: https://v3-apidocs.cloudfoundry.org/version/3.89.0/index.html#replace-all-destinations-for-a-route
2. You could `cf unmap-route` and `cf map-route` to remap the route after the Docker app is "staged". The `Route` CRD will be created with the correct port in this case.
3. Listen on and expose the default port: `8080`

---

### What can we do on the CAKE team to fix this?

1. Once we enhance the route syncer to [work with route destinations](https://www.pivotaltracker.com/story/show/175336568) this will be "fixed" in an eventually consistent way. The `Route` will still initially be made with the incorrect port, but eventually the `Route` syncer will discover that the actual state of the CRD doesn't match the desired state in CCDB and update it.
2. We could attempt to update the `Route` CRD whenever the app `Process` is started. This is similar to how it works today with Diego in CF for VMs since routing information is included with the LRP definition.
3. Special case Docker apps and update their `Route`s as part of the staging completion callback? (sounds a bit sketchy)
4. ??? (we're only limited by our imagination here)

**Comment by tcdowney** [comment] 2020-10-21 21:30
cc @piyalibanerjee for awareness

**Comment by piyalibanerjee** [comment] 2020-12-02 21:27
Closing this issue since it's been fixed by the route syncer now syncing route destinations (see option 1 in the "What can we do on the CAKE team to fix this" section above).

**Closed by piyalibanerjee** 2020-12-02 21:27 UTC
Labels: unscheduled
