### ISSUE TITLE
`cf push` timeout related to capi-api-server

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/capi-k8s-release#28] opened 2020-04-06 22:31 UTC
We noticed a [failed build of smoke-tests in our CI](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/stability-test-cf-for-k8s/builds/2263) recently. We dug into it, thinking that it might be another instance of the issue reported in #27, but found that, in this case, the `capi-kpack-watcher` had not restarted:
```console
  capi-kpack-watcher:
    Container ID:   docker://8c5ae51161a1722dda5ed0c38c774d401914dd05413c0fbb4b2df1a3caeea90e
    Image:          cloudfoundry/capi-kpack-watcher:956150dae0a95dcdf3c1f29c23c3bf11db90f7a0@sha256:67125e0d3a4026a23342d80e09aad9284c08ab4f7b3d9a993ae66e403d5d0796
    Image ID:       docker-pullable://cloudfoundry/capi-kpack-watcher@sha256:67125e0d3a4026a23342d80e09aad9284c08ab4f7b3d9a993ae66e403d5d0796
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 02 Apr 2020 19:16:16 -0700
    Ready:          True
    Restart Count:  0
...
```
When we dug more into the logs from the `capi-kpack-watcher`, we saw that it had successfully completed staging the app, but received a 404 when it went to post the update with the image ID back to the API server. When we looked at the logs from the two `capi-api-server` pods, we saw that one pod had handled the initial POST request (presumably from the CLI) to start staging the app, and the other pod had handled the PATCH request from the watcher to update the app state. Please see [this gist](https://gist.github.com/davewalter/aadab8239443f9032b2328a934537b98) for details. To aid with debugging, this test ran with https://github.com/cloudfoundry/cf-for-k8s/commit/6c9f5cd30acbfe0644bc323da73444b9c41e4617, which uses capi-k8s-release @ https://github.com/cloudfoundry/capi-k8s-release/commit/29980921bca735de3000b32a0defb319ce6522d5.

**Comment by davewalter** [comment] 2020-04-06 23:08
Follow-up [Slack conversation](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1586212449062100) with @jspawar.

**Comment by kramerul** [comment] 2020-04-21 15:20
As far as I can see in the code, there could be a lot of reasons why this could happen:
* there is no retry done, if the communication fails to CAPI
* during startup, there is no update call happening to CAPI
* if an update event got lost (downtime) it will never be reported to CAPI

In general it would be more robust to switch to a level triggered implementation using the [kubernetes controller runtime](https://github.com/kubernetes-sigs/controller-runtime). You could add an annotation to the `kpack-build` if the status was successfully reported to CAPI.
This could also be achieved using the normal k8s-go-client but in my point of view it's easier to use the the controller runtime.

**Comment by selzoc** [comment] 2020-05-11 19:18
@davewalter have y'all seen this failure recently?

@kramerul we have created a story to incorporate some of your suggestions: https://www.pivotaltracker.com/story/show/172776428

Going to close this now, please re-open if this happens again

**Closed by selzoc** 2020-05-11 19:18 UTC
Labels: in progress

**Comment by kramerul** [comment] 2020-05-12 04:59
@selzoc, the problem is still there. See https://github.com/cloudfoundry/cf-for-k8s/issues/140.

@aashah is currently analyzing the problem on our cluster.
